name: dlenv_310
channels:
  - pytorch
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - debugpy=1.8.11
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - jedi=0.19.2
  - jinja2=3.1.5
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - lcms2=2.16
  - lerc=4.0.0
  - libcxx=14.0.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libjpeg-turbo=2.0.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.2
  - parso=0.8.4
  - pexpect=4.8.0
  - pillow=11.1.0
  - pip=25.0
  - platformdirs=3.10.0
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0post0
  - pytorch=2.2.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.8.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - sympy=1.13.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.2.2
  - torchvision=0.17.2
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - wcwidth=0.2.5
  - wheel=0.45.1
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstd=1.5.6
